### ISSUE TITLE
SSL Error - 'certificate verify failed'

### ISSUE THREAD

**Issue by RichFoley** [w1ll1am23/pydukeenergy#2]
I am using the home assistant integration and am now getting SLL errors. This started on 12-21-2019.

`2020-01-16 17:47:27 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform duke_energy
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.duke-energy.com', port=443): Max retries exceeded with url: /form/Login/GetAccountValidationMessage (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/duke_energy/sensor.py", line 28, in setup_platform
    config[CONF_USERNAME], config[CONF_PASSWORD], update_interval=120
  File "/usr/local/lib/python3.7/site-packages/pydukeenergy/api.py", line 48, in __init__
    if not self._login():
  File "/usr/local/lib/python3.7/site-packages/pydukeenergy/api.py", line 137, in _login
    response = self.session.post(LOGIN_URL, data=data, headers=headers, timeout=10)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 581, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.duke-energy.com', port=443): Max retries exceeded with url: /form/Login/GetAccountValidationMessage (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))`

**Comment by w1ll1am23** [comment]
Just saw this I will try to figure it out over the next couple days. Looks like they changed some of the code on the site which is why it isn't working I will have to get an updated version out. I will let you know what I find.

**Comment by FreeWillyB** [comment]
Any update on this?

**Comment by w1ll1am23** [comment]
I have looked at it some. Their API changed a little, but using the new one I still get SSL errors. I think something changed in a recent version of Python. I will have to look in to it some more.

**Comment by FreeWillyB** [comment]
I’m actually digging into it as well. I’ve noticed that on my MacBook, I’m getting SSL very errors in Chrome but not Firefox or Safari. It looks like there is some kind of misconfiguration error. 

Also I noticed they changed the login from from “Login” to “SignIn” 

Will Blanton
jwblant@gmail.com

**Comment by FreeWillyB** [comment]
I think you’re right. I’m noticing some SSL errors and it looks like a few URL slugs have changed as well. I’ll see if I can get something working. 

Will Blanton
jwblant@gmail.com

**Comment by w1ll1am23** [comment]
Great! Glad you're taking a look. Yeah I noticed the signin/login thing too. 

I didn't test in a browser interesting you're seeing an issue there...

**Comment by FreeWillyB** [comment]
Just created a pull request. It's my first time forking a repo, so hopefully I did it right and you can see the changes. I've got most of functional, at least I think so. But I was still getting a few errors. But feel free to look it over and see what you think.

On another note, I noticed you were scraping using BS4 to get the meter info from the usage analysis page, but I have NO CLUE how that ever worked. They are currently using javascript to fill that drop down list, so without using Selenium, I don't even know of a way to get those values using python. For that reason, I just added a way for the users to manually input their own meter numbers. Not ideal, but it gets it working.

Also added a way for the user to ignore SSL verification if they wish. It's still on by default, but it can be bypassed by using the "verify_ssl=False" flag in the constructor.
